### ISSUE TITLE
Utilisation avec plusieurs freebox

### ISSUE THREAD

**Issue by mika-nt28** [MaximeCheramy/remotefreebox#1]
Bonjour,

J'essaye d'utilisé ton code pour piloté mes Freebox
J'ai l'option multi-TV, j'ai donc une Révolution et un mini 4k

Je voudrais pouvoir sélectionné la Freebox qui m’intéresse.
Pour cela je pensais que ce code me renvoyait toutes mes freebox
`from remotefreebox.detectserver import detect
fbx = detect() ` 
En réalité il me renvoie rien si je fait un `print fbx`

Est ce moi qui utilise mal ton framework?

**Comment by MaximeCheramy** [comment]
Désolé je n'avais pas vu ton message. Je n'ai qu'une seule freebox donc c'est un peu compliqué pour moi de tester...
